---
title: "CodingChallenge_DataWrangling"
author: "Vaibhav B. Shelar"
date: "2025-03-23"
output: 
      html_document: 
      variant: gfm
      md_document:
      word_document: default
      toc: true
      toc_float: true
      pdf_document: default
---


```{r}
library(tidyverse)
```

```{r}
### Q2

# load csv file

diversity_data <- read.csv("DiversityData.csv")

meta_data <- read.csv("Metadata.csv")

# join the dataframe by the common column

alpha <- left_join(diversity_data, meta_data, by = "Code")
```

```{r}
### Q3

# a)

library(dplyr)

# calculating Pielou's evenness index

alpha$Pielou_evenness <- log(alpha$richness)

# Create a new column called Pielou_evenness and name the dataframe as alpha_even
alpha_even <- alpha %>%
              mutate(Pielou_evenness = shannon / log(richness))
```

### Q4

```{r}
# summarizing Pielou's evenness by Crop and Time_Point and Summarize the data

alpha_average <- alpha_even %>%
                  group_by(Crop, Time_Point) %>%
                  summarise(mean_even = mean(Pielou_evenness),
                  count_even = n(),
                  sd.dev = sd(Pielou_evenness),
                  sd.err = sd(Pielou_evenness)/sqrt(n()))
```

### Q5

# Calculate the difference between the soybean column, the soil column, and the difference between the cotton column and the soil column

```{r}
alpha_average2 <- alpha_average %>%
                  select(Time_Point, Crop, mean_even) %>%
                  pivot_wider(names_from = Crop, values_from = mean_even) %>%
                  mutate(diff.cotton.even = Soil - Cotton,
                         diff.soybean.even = Soil - Soybean)
```

### Q6

# Connecting it to plots

```{r}
alpha_average2 %>%
  select(Time_Point, diff.cotton.even, diff.soybean.even) %>%  # Select relevant columns
  pivot_longer(cols = c(diff.cotton.even, diff.soybean.even), names_to = "diff") %>%
  ggplot(aes(x = Time_Point, y = value, color = diff)) +
  geom_line(size = 1) +  # Line plot
  theme_minimal() +  # Clean theme
  labs(
    x = "Time (hrs)",
    y = "Difference from soil in Pielou’s evenness",
    color = "diff"
  ) + 
  theme(legend.position = "right")
```


