---
title: "HomeworkIterationsFunctions"
author: "Vaibhav B. Shelar"
date: "2025-03-27"
output: 
      html_document: 
      variant: gfm
      md_document:
      pdf_document: default
      toc: true
      toc_float: true
      word_document: default
---

```{r}
#(5*degree_f - 32)/9
(5*(10 - 32)/9)

(5*(36 - 32)/9)
(5*(39 - 32)/9)
(5*(40 - 32)/9)
(5*(42 - 32)/9)
```
```{r}
# Creating a function 

F_to_C <- function(f_temp){ #f_temp is an input
  celsius <- (5*(f_temp - 32)/9)
  return(celsius) # This is for output
}
```

```{r}
# Function application 

F_to_C(32)
F_to_C(80)
```

```{r}
# iteration function in base R 

rep("A", 3)
rep(c("A", "B"), 10) # repeat A and B 10 times

rep(c(1, 3, 2, 5), 4, each = 10) # repeat each element 10 times
```

```{r}
# Creating a sequence of numbers

1:7 

seq(from = 1, to = 7) # same as above
seq(from = 0, to = 10, by = 2) # 0, 2, 4, 6, 8, 10


LETTERS
seq_along(LETTERS) # 1 to 26
```

```{r}
# The for loop

for (i in 1:10){
  print(i*2)
}

for (i in -30:100){
  result <- F_to_C(i)
  print(result)
}


celsius.df <- NULL
for (i in -30:100){
  result <- data.frame(F_to_C(i), i)
  colnames(result) <- c("C", "F")
  celsius.df <- rbind.data.frame(celsius.df, result) # rbind is a row bind function
}
```

```{r}
library(tidyverse)
library(drc)
EC50.data <- read.csv("EC50_all.csv")

str(EC50.data)

isolate1 <- drm(100 * EC50.data$relgrowth[EC50.data$is == "ILSO_5-41c"] ~ 
                  EC50.data$conc[EC50.data$is == "ILSO_5-41c"], 
                fct = LL.4(fixed = c(NA, NA, NA, NA), 
                           names = c("Slope", "Lower", "Upper", "EC50")), 
                na.action = na.omit)
```

```{r}
# summary.mef.fit for 'summary of fit'

summary.fit <- data.frame(summary(isolate1)[[3]]) # [[]] is for extracting the third element of the summary(isolate1) function

EC50 <- ED(isolate1, respLev = c(50), type = "relative",
           interval = "delta")[[1]]

EC50.114 <- NULL
nm <- unique(EC50.data$is)
for (i in seq_along(nm)) {
  isolate1 <- drm(100 * EC50.data$relgrowth[EC50.data$is == nm[[i]]] ~ 
                    EC50.data$conc[EC50.data$is == nm[[i]]], 
                  fct = LL.4(fixed = c(NA, NA, NA, NA), 
                             names = c("Slope", "Lower", "Upper", "EC50")), 
                  na.action = na.omit)
}
print(nm[[i]])
  
summary.fit <- data.frame(summary(isolate1)[[3]])

EC50 <- ED(isolate1, respLev = c(50), type = "relative", 
             interval = "delta")[[1]] 
isolate.ec_1 <- data.frame(nm[[i]], EC50)
EC50.114 <- rbind.data.frame(EC50.114, isolate.ec_1)
        EC50
```

```{r}
# Using map function from purrr package

EC50.data %>%
  group_by(is) %>%
  nest() %>%
  mutate(ll.4.mod = map(data, ~drm(.$relgrowth ~ .$conc, # map told us that it iterate and '.' symbol inherits all the data columns from previous dataset
                                   fct = LL.4(fixed = c(NA, NA, NA, NA), 
                                              names = c("Slope", "Lower", "Upper", "EC50"))))) %>%
  mutate(ec50 = map(ll.4.mod, ~ED(., 
                                  respLev = c(50), 
                                  type = "relative",
                                  interval = "delta")[[1]])) %>%
  unnest(ec50)
```




